/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`delete_plugins_plugin_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeletePluginsPluginIdError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_plugins`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPluginsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_plugins_plugin_id_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPluginsPluginIdStatusError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_plugins_plugin_id_disable`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostPluginsPluginIdDisableError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_plugins_plugin_id_enable`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostPluginsPluginIdEnableError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_plugins_plugin_id_reload`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostPluginsPluginIdReloadError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`put_plugins_plugin_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PutPluginsPluginIdError {
    DefaultResponse(models::PluginInfo),
    UnknownValue(serde_json::Value),
}


/// Disables a plugin on the Gerrit server.
pub fn delete_plugins_plugin_id(configuration: &configuration::Configuration, plugin_id: &str) -> Result<models::PluginInfo, Error<DeletePluginsPluginIdError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_plugin_id = plugin_id;

    let uri_str = format!("{}/plugins/{plugin_id}", configuration.base_path, plugin_id=crate::apis::urlencode(p_path_plugin_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let content = crate::xssi::strip(&content).to_string();
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PluginInfo`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PluginInfo`")))),
        }
    } else {
        let content = resp.text()?;
        let content = crate::xssi::strip(&content).to_string();
        let entity: Option<DeletePluginsPluginIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Lists the plugins installed on the Gerrit server. Only the enabled plugins are returned unless the all option is specified.
pub fn get_plugins(configuration: &configuration::Configuration, all: Option<bool>, limit: Option<i32>, r#match: Option<&str>, prefix: Option<&str>, r: Option<&str>, start: Option<i32>) -> Result<std::collections::HashMap<String, models::PluginInfo>, Error<GetPluginsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_all = all;
    let p_query_limit = limit;
    let p_query_match = r#match;
    let p_query_prefix = prefix;
    let p_query_r = r;
    let p_query_start = start;

    let uri_str = format!("{}/plugins", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_all {
        req_builder = req_builder.query(&[("all", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_match {
        req_builder = req_builder.query(&[("match", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_prefix {
        req_builder = req_builder.query(&[("prefix", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_r {
        req_builder = req_builder.query(&[("r", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_start {
        req_builder = req_builder.query(&[("start", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let content = crate::xssi::strip(&content).to_string();
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, models::PluginInfo&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, models::PluginInfo&gt;`")))),
        }
    } else {
        let content = resp.text()?;
        let content = crate::xssi::strip(&content).to_string();
        let entity: Option<GetPluginsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub fn get_plugins_plugin_id_status(configuration: &configuration::Configuration, plugin_id: &str) -> Result<models::PluginInfo, Error<GetPluginsPluginIdStatusError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_plugin_id = plugin_id;

    let uri_str = format!("{}/plugins/{plugin_id}/status", configuration.base_path, plugin_id=crate::apis::urlencode(p_path_plugin_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let content = crate::xssi::strip(&content).to_string();
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PluginInfo`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PluginInfo`")))),
        }
    } else {
        let content = resp.text()?;
        let content = crate::xssi::strip(&content).to_string();
        let entity: Option<GetPluginsPluginIdStatusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub fn post_plugins_plugin_id_disable(configuration: &configuration::Configuration, plugin_id: &str) -> Result<models::PluginInfo, Error<PostPluginsPluginIdDisableError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_plugin_id = plugin_id;

    let uri_str = format!("{}/plugins/{plugin_id}/disable", configuration.base_path, plugin_id=crate::apis::urlencode(p_path_plugin_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let content = crate::xssi::strip(&content).to_string();
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PluginInfo`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PluginInfo`")))),
        }
    } else {
        let content = resp.text()?;
        let content = crate::xssi::strip(&content).to_string();
        let entity: Option<PostPluginsPluginIdDisableError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub fn post_plugins_plugin_id_enable(configuration: &configuration::Configuration, plugin_id: &str) -> Result<models::PluginInfo, Error<PostPluginsPluginIdEnableError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_plugin_id = plugin_id;

    let uri_str = format!("{}/plugins/{plugin_id}/enable", configuration.base_path, plugin_id=crate::apis::urlencode(p_path_plugin_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let content = crate::xssi::strip(&content).to_string();
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PluginInfo`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PluginInfo`")))),
        }
    } else {
        let content = resp.text()?;
        let content = crate::xssi::strip(&content).to_string();
        let entity: Option<PostPluginsPluginIdEnableError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub fn post_plugins_plugin_id_reload(configuration: &configuration::Configuration, plugin_id: &str) -> Result<models::PluginInfo, Error<PostPluginsPluginIdReloadError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_plugin_id = plugin_id;

    let uri_str = format!("{}/plugins/{plugin_id}/reload", configuration.base_path, plugin_id=crate::apis::urlencode(p_path_plugin_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let content = crate::xssi::strip(&content).to_string();
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PluginInfo`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PluginInfo`")))),
        }
    } else {
        let content = resp.text()?;
        let content = crate::xssi::strip(&content).to_string();
        let entity: Option<PostPluginsPluginIdReloadError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Installs a new plugin on the Gerrit server. If a plugin with the specified name already exists it is overwritten. Note: if the plugin provides its own name in the MANIFEST file, then the plugin name from the MANIFEST file has precedence over the \\{plugin-id\\} above.
pub fn put_plugins_plugin_id(configuration: &configuration::Configuration, plugin_id: &str, install_plugin_input: Option<models::InstallPluginInput>) -> Result<models::PluginInfo, Error<PutPluginsPluginIdError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_plugin_id = plugin_id;
    let p_body_install_plugin_input = install_plugin_input;

    let uri_str = format!("{}/plugins/{plugin_id}", configuration.base_path, plugin_id=crate::apis::urlencode(p_path_plugin_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    req_builder = req_builder.json(&p_body_install_plugin_input);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let content = crate::xssi::strip(&content).to_string();
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PluginInfo`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PluginInfo`")))),
        }
    } else {
        let content = resp.text()?;
        let content = crate::xssi::strip(&content).to_string();
        let entity: Option<PutPluginsPluginIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

