/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountsInfo {
    #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
    pub visibility: Option<models::AccountVisibility>,
    #[serde(rename = "default_display_name", skip_serializing_if = "Option::is_none")]
    pub default_display_name: Option<models::AccountDefaultDisplayName>,
}

impl AccountsInfo {
    pub fn new() -> AccountsInfo {
        AccountsInfo {
            visibility: None,
            default_display_name: None,
        }
    }
}

