/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountVisibility {
    #[serde(rename = "ALL")]
    All,
    #[serde(rename = "SAME_GROUP")]
    SameGroup,
    #[serde(rename = "VISIBLE_GROUP")]
    VisibleGroup,
    #[serde(rename = "NONE")]
    None,

}

impl std::fmt::Display for AccountVisibility {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::All => write!(f, "ALL"),
            Self::SameGroup => write!(f, "SAME_GROUP"),
            Self::VisibleGroup => write!(f, "VISIBLE_GROUP"),
            Self::None => write!(f, "NONE"),
        }
    }
}

impl Default for AccountVisibility {
    fn default() -> AccountVisibility {
        Self::All
    }
}

