/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplyPatchPatchSetInput {
    #[serde(rename = "patch", skip_serializing_if = "Option::is_none")]
    pub patch: Option<Box<models::ApplyPatchInput>>,
    #[serde(rename = "commit_message", skip_serializing_if = "Option::is_none")]
    pub commit_message: Option<String>,
    #[serde(rename = "base", skip_serializing_if = "Option::is_none")]
    pub base: Option<String>,
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<Box<models::AccountInput>>,
    #[serde(rename = "response_format_options", skip_serializing_if = "Option::is_none")]
    pub response_format_options: Option<Vec<models::ListChangesOption>>,
    #[serde(rename = "amend", skip_serializing_if = "Option::is_none")]
    pub amend: Option<bool>,
}

impl ApplyPatchPatchSetInput {
    pub fn new() -> ApplyPatchPatchSetInput {
        ApplyPatchPatchSetInput {
            patch: None,
            commit_message: None,
            base: None,
            author: None,
            response_format_options: None,
            amend: None,
        }
    }
}

