/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthInfo {
    #[serde(rename = "auth_type", skip_serializing_if = "Option::is_none")]
    pub auth_type: Option<models::AuthType>,
    #[serde(rename = "use_contributor_agreements", skip_serializing_if = "Option::is_none")]
    pub use_contributor_agreements: Option<bool>,
    #[serde(rename = "contributor_agreements", skip_serializing_if = "Option::is_none")]
    pub contributor_agreements: Option<Vec<models::AgreementInfo>>,
    #[serde(rename = "editable_account_fields", skip_serializing_if = "Option::is_none")]
    pub editable_account_fields: Option<Vec<models::AccountFieldName>>,
    #[serde(rename = "login_url", skip_serializing_if = "Option::is_none")]
    pub login_url: Option<String>,
    #[serde(rename = "login_text", skip_serializing_if = "Option::is_none")]
    pub login_text: Option<String>,
    #[serde(rename = "switch_account_url", skip_serializing_if = "Option::is_none")]
    pub switch_account_url: Option<String>,
    #[serde(rename = "register_url", skip_serializing_if = "Option::is_none")]
    pub register_url: Option<String>,
    #[serde(rename = "register_text", skip_serializing_if = "Option::is_none")]
    pub register_text: Option<String>,
    #[serde(rename = "edit_full_name_url", skip_serializing_if = "Option::is_none")]
    pub edit_full_name_url: Option<String>,
    #[serde(rename = "http_password_url", skip_serializing_if = "Option::is_none")]
    pub http_password_url: Option<String>,
    #[serde(rename = "git_basic_auth_policy", skip_serializing_if = "Option::is_none")]
    pub git_basic_auth_policy: Option<models::GitBasicAuthPolicy>,
    #[serde(rename = "max_token_lifetime", skip_serializing_if = "Option::is_none")]
    pub max_token_lifetime: Option<i32>,
}

impl AuthInfo {
    pub fn new() -> AuthInfo {
        AuthInfo {
            auth_type: None,
            use_contributor_agreements: None,
            contributor_agreements: None,
            editable_account_fields: None,
            login_url: None,
            login_text: None,
            switch_account_url: None,
            register_url: None,
            register_text: None,
            edit_full_name_url: None,
            http_password_url: None,
            git_basic_auth_policy: None,
            max_token_lifetime: None,
        }
    }
}

