/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutoCloseableChangesCheckInput {
    #[serde(rename = "fix", skip_serializing_if = "Option::is_none")]
    pub fix: Option<bool>,
    #[serde(rename = "branch", skip_serializing_if = "Option::is_none")]
    pub branch: Option<String>,
    #[serde(rename = "skip_commits", skip_serializing_if = "Option::is_none")]
    pub skip_commits: Option<i32>,
    #[serde(rename = "max_commits", skip_serializing_if = "Option::is_none")]
    pub max_commits: Option<i32>,
}

impl AutoCloseableChangesCheckInput {
    pub fn new() -> AutoCloseableChangesCheckInput {
        AutoCloseableChangesCheckInput {
            fix: None,
            branch: None,
            skip_commits: None,
            max_commits: None,
        }
    }
}

