/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchSubmitRequirementInput {
    #[serde(rename = "commit_message", skip_serializing_if = "Option::is_none")]
    pub commit_message: Option<String>,
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<Vec<String>>,
    #[serde(rename = "create", skip_serializing_if = "Option::is_none")]
    pub create: Option<Vec<models::SubmitRequirementInput>>,
    #[serde(rename = "update", skip_serializing_if = "Option::is_none")]
    pub update: Option<std::collections::HashMap<String, models::SubmitRequirementInput>>,
}

impl BatchSubmitRequirementInput {
    pub fn new() -> BatchSubmitRequirementInput {
        BatchSubmitRequirementInput {
            commit_message: None,
            delete: None,
            create: None,
            update: None,
        }
    }
}

