/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlameInfo {
    /// The author of the commit.
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    /// The id of the commit.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Commit time.
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i32>,
    /// The commit message.
    #[serde(rename = "commit_msg", skip_serializing_if = "Option::is_none")]
    pub commit_msg: Option<String>,
    /// The blame row coordinates as RangeInfo entities.
    #[serde(rename = "ranges", skip_serializing_if = "Option::is_none")]
    pub ranges: Option<Vec<models::RangeInfo>>,
}

impl BlameInfo {
    pub fn new() -> BlameInfo {
        BlameInfo {
            author: None,
            id: None,
            time: None,
            commit_msg: None,
            ranges: None,
        }
    }
}

