/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BranchInput {
    #[serde(rename = "revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    #[serde(rename = "create_empty_commit", skip_serializing_if = "Option::is_none")]
    pub create_empty_commit: Option<bool>,
    #[serde(rename = "ref", skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
    #[serde(rename = "source_ref", skip_serializing_if = "Option::is_none")]
    pub source_ref: Option<String>,
    #[serde(rename = "validation_options", skip_serializing_if = "Option::is_none")]
    pub validation_options: Option<std::collections::HashMap<String, String>>,
}

impl BranchInput {
    pub fn new() -> BranchInput {
        BranchInput {
            revision: None,
            create_empty_commit: None,
            r#ref: None,
            source_ref: None,
            validation_options: None,
        }
    }
}

