/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CacheInfo {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::CacheType>,
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<Box<models::EntriesInfo>>,
    #[serde(rename = "average_get", skip_serializing_if = "Option::is_none")]
    pub average_get: Option<String>,
    #[serde(rename = "hit_ratio", skip_serializing_if = "Option::is_none")]
    pub hit_ratio: Option<Box<models::HitRatioInfo>>,
}

impl CacheInfo {
    pub fn new() -> CacheInfo {
        CacheInfo {
            name: None,
            r#type: None,
            entries: None,
            average_get: None,
            hit_ratio: None,
        }
    }
}

