/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChangeType {
    #[serde(rename = "ADDED")]
    Added,
    #[serde(rename = "MODIFIED")]
    Modified,
    #[serde(rename = "DELETED")]
    Deleted,
    #[serde(rename = "RENAMED")]
    Renamed,
    #[serde(rename = "COPIED")]
    Copied,
    #[serde(rename = "REWRITE")]
    Rewrite,

}

impl std::fmt::Display for ChangeType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Added => write!(f, "ADDED"),
            Self::Modified => write!(f, "MODIFIED"),
            Self::Deleted => write!(f, "DELETED"),
            Self::Renamed => write!(f, "RENAMED"),
            Self::Copied => write!(f, "COPIED"),
            Self::Rewrite => write!(f, "REWRITE"),
        }
    }
}

impl Default for ChangeType {
    fn default() -> ChangeType {
        Self::Added
    }
}

