/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeMessageInfo {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<Box<models::AccountInfo>>,
    #[serde(rename = "real_author", skip_serializing_if = "Option::is_none")]
    pub real_author: Option<Box<models::AccountInfo>>,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "accounts_in_message", skip_serializing_if = "Option::is_none")]
    pub accounts_in_message: Option<Vec<models::AccountInfo>>,
    #[serde(rename = "_revision_number", skip_serializing_if = "Option::is_none")]
    pub _revision_number: Option<i32>,
}

impl ChangeMessageInfo {
    pub fn new() -> ChangeMessageInfo {
        ChangeMessageInfo {
            id: None,
            tag: None,
            author: None,
            real_author: None,
            date: None,
            message: None,
            accounts_in_message: None,
            _revision_number: None,
        }
    }
}

