/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeInput {
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(rename = "branch", skip_serializing_if = "Option::is_none")]
    pub branch: Option<String>,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(rename = "topic", skip_serializing_if = "Option::is_none")]
    pub topic: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::ChangeStatus>,
    #[serde(rename = "is_private", skip_serializing_if = "Option::is_none")]
    pub is_private: Option<bool>,
    #[serde(rename = "work_in_progress", skip_serializing_if = "Option::is_none")]
    pub work_in_progress: Option<bool>,
    #[serde(rename = "base_change", skip_serializing_if = "Option::is_none")]
    pub base_change: Option<String>,
    #[serde(rename = "base_commit", skip_serializing_if = "Option::is_none")]
    pub base_commit: Option<String>,
    #[serde(rename = "new_branch", skip_serializing_if = "Option::is_none")]
    pub new_branch: Option<bool>,
    #[serde(rename = "validation_options", skip_serializing_if = "Option::is_none")]
    pub validation_options: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "custom_keyed_values", skip_serializing_if = "Option::is_none")]
    pub custom_keyed_values: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "merge", skip_serializing_if = "Option::is_none")]
    pub merge: Option<Box<models::MergeInput>>,
    #[serde(rename = "patch", skip_serializing_if = "Option::is_none")]
    pub patch: Option<Box<models::ApplyPatchInput>>,
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<Box<models::AccountInput>>,
    #[serde(rename = "response_format_options", skip_serializing_if = "Option::is_none")]
    pub response_format_options: Option<Vec<models::ListChangesOption>>,
    #[serde(rename = "notify", skip_serializing_if = "Option::is_none")]
    pub notify: Option<models::NotifyHandling>,
    #[serde(rename = "notify_details", skip_serializing_if = "Option::is_none")]
    pub notify_details: Option<std::collections::HashMap<String, models::NotifyInfo>>,
}

impl ChangeInput {
    pub fn new() -> ChangeInput {
        ChangeInput {
            project: None,
            branch: None,
            subject: None,
            topic: None,
            status: None,
            is_private: None,
            work_in_progress: None,
            base_change: None,
            base_commit: None,
            new_branch: None,
            validation_options: None,
            custom_keyed_values: None,
            merge: None,
            patch: None,
            author: None,
            response_format_options: None,
            notify: None,
            notify_details: None,
        }
    }
}

