/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChangeStatus {
    #[serde(rename = "NEW")]
    New,
    #[serde(rename = "MERGED")]
    Merged,
    #[serde(rename = "ABANDONED")]
    Abandoned,

}

impl std::fmt::Display for ChangeStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::New => write!(f, "NEW"),
            Self::Merged => write!(f, "MERGED"),
            Self::Abandoned => write!(f, "ABANDONED"),
        }
    }
}

impl Default for ChangeStatus {
    fn default() -> ChangeStatus {
        Self::New
    }
}

