/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckProjectInput {
    #[serde(rename = "auto_closeable_changes_check", skip_serializing_if = "Option::is_none")]
    pub auto_closeable_changes_check: Option<Box<models::AutoCloseableChangesCheckInput>>,
}

impl CheckProjectInput {
    pub fn new() -> CheckProjectInput {
        CheckProjectInput {
            auto_closeable_changes_check: None,
        }
    }
}

