/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommentInfo {
    /// The author of the message as an AccountInfo entity. + Unset for draft comments, assumed to be the calling user.
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<Box<models::AccountInfo>>,
    /// Value of the tag field from ReviewInput set while posting the review. NOTE: To apply different tags on different votes/comments multiple invocations of the REST call are required.
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    /// Available with the list change comments endpoint. Contains the id of the change message that this comment is linked to.
    #[serde(rename = "change_message_id", skip_serializing_if = "Option::is_none")]
    pub change_message_id: Option<String>,
    /// Whether or not the comment must be addressed by the user. The state of resolution of a comment thread is stored in the last comment in that thread chronologically.
    #[serde(rename = "unresolved", skip_serializing_if = "Option::is_none")]
    pub unresolved: Option<bool>,
    /// A list of ContextLine containing the lines of the source file where the comment was written. Available only if the \"enable-context\" parameter (see List Change Comments) is set.
    #[serde(rename = "context_lines", skip_serializing_if = "Option::is_none")]
    pub context_lines: Option<Vec<models::ContextLineInfo>>,
    /// Mime type of the file where the comment is written. Available only if the \"enable-context\" parameter (see List Change Comments) is set.
    #[serde(rename = "source_content_type", skip_serializing_if = "Option::is_none")]
    pub source_content_type: Option<String>,
    /// The patch set number for the comment; only set in contexts where + comments may be returned for multiple patch sets.
    #[serde(rename = "patch_set", skip_serializing_if = "Option::is_none")]
    pub patch_set: Option<i32>,
    /// The URL encoded UUID of the comment.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The file path for which the inline comment was done. + Not set if returned in a map where the key is the file path.
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// The side on which the comment was added. + Allowed values are REVISION and PARENT. + If not set, the default is REVISION.
    #[serde(rename = "side", skip_serializing_if = "Option::is_none")]
    pub side: Option<models::Side>,
    /// The 1-based parent number. Used only for merge commits when side == PARENT. When not set the comment is for the auto-merge tree.
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<i32>,
    /// The number of the line for which the comment was done. + If range is set, this equals the end line of the range. + If neither line nor range is set, it's a file comment.
    #[serde(rename = "line", skip_serializing_if = "Option::is_none")]
    pub line: Option<i32>,
    /// The range of the comment as a CommentRange entity.
    #[serde(rename = "range", skip_serializing_if = "Option::is_none")]
    pub range: Option<Box<models::Range>>,
    /// The URL encoded UUID of the comment to which this comment is a reply.
    #[serde(rename = "in_reply_to", skip_serializing_if = "Option::is_none")]
    pub in_reply_to: Option<String>,
    /// The timestamp of when this comment was written.
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
    /// The comment message.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// Hex commit SHA-1 (40 characters string) of the commit of the patchset to which this comment applies.
    #[serde(rename = "commit_id", skip_serializing_if = "Option::is_none")]
    pub commit_id: Option<String>,
    /// Suggested fixes for this comment as a list of FixSuggestionInfo entities.
    #[serde(rename = "fix_suggestions", skip_serializing_if = "Option::is_none")]
    pub fix_suggestions: Option<Vec<models::FixSuggestionInfo>>,
    /// Whether the comment was created by an AI agent. Not set if false.
    #[serde(rename = "is_ai", skip_serializing_if = "Option::is_none")]
    pub is_ai: Option<bool>,
}

impl CommentInfo {
    pub fn new() -> CommentInfo {
        CommentInfo {
            author: None,
            tag: None,
            change_message_id: None,
            unresolved: None,
            context_lines: None,
            source_content_type: None,
            patch_set: None,
            id: None,
            path: None,
            side: None,
            parent: None,
            line: None,
            range: None,
            in_reply_to: None,
            updated: None,
            message: None,
            commit_id: None,
            fix_suggestions: None,
            is_ai: None,
        }
    }
}

