/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommitInfo {
    #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
    pub commit: Option<String>,
    #[serde(rename = "parents", skip_serializing_if = "Option::is_none")]
    pub parents: Option<Vec<models::CommitInfo>>,
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<Box<models::GitPerson>>,
    #[serde(rename = "committer", skip_serializing_if = "Option::is_none")]
    pub committer: Option<Box<models::GitPerson>>,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "web_links", skip_serializing_if = "Option::is_none")]
    pub web_links: Option<Vec<models::WebLinkInfo>>,
    #[serde(rename = "resolve_conflicts_web_links", skip_serializing_if = "Option::is_none")]
    pub resolve_conflicts_web_links: Option<Vec<models::WebLinkInfo>>,
}

impl CommitInfo {
    pub fn new() -> CommitInfo {
        CommitInfo {
            commit: None,
            parents: None,
            author: None,
            committer: None,
            subject: None,
            message: None,
            web_links: None,
            resolve_conflicts_web_links: None,
        }
    }
}

