/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommitMessageInfo {
    /// The subject of the change (first line of the commit message).
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    /// Full commit message of the change.
    #[serde(rename = "full_message", skip_serializing_if = "Option::is_none")]
    pub full_message: Option<String>,
    /// The footers from the commit message as a map of key-value pairs. If there are multiple footers with the same key, only the last footer with that key is returned.
    #[serde(rename = "footers", skip_serializing_if = "Option::is_none")]
    pub footers: Option<std::collections::HashMap<String, String>>,
}

impl CommitMessageInfo {
    pub fn new() -> CommitMessageInfo {
        CommitMessageInfo {
            subject: None,
            full_message: None,
            footers: None,
        }
    }
}

