/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommitMessageInput {
    /// New commit message.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// Notify handling that defines to whom email notifications should be sent after the commit message was updated. + Allowed values are NONE, OWNER, OWNER_REVIEWERS and ALL. + If not set, the default is OWNER for WIP changes and ALL otherwise.
    #[serde(rename = "notify", skip_serializing_if = "Option::is_none")]
    pub notify: Option<models::NotifyHandling>,
    /// Additional information about whom to notify about the update as a map of recipient type to NotifyInfo entity.
    #[serde(rename = "notify_details", skip_serializing_if = "Option::is_none")]
    pub notify_details: Option<std::collections::HashMap<String, models::NotifyInfo>>,
    /// New message is committed using this email address. Only the registered emails of the calling user are considered valid.
    #[serde(rename = "committer_email", skip_serializing_if = "Option::is_none")]
    pub committer_email: Option<String>,
}

impl CommitMessageInput {
    pub fn new() -> CommitMessageInput {
        CommitMessageInput {
            message: None,
            notify: None,
            notify_details: None,
            committer_email: None,
        }
    }
}

