/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigParameterInfo {
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "warning", skip_serializing_if = "Option::is_none")]
    pub warning: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::ProjectConfigEntryType>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "editable", skip_serializing_if = "Option::is_none")]
    pub editable: Option<bool>,
    #[serde(rename = "inheritable", skip_serializing_if = "Option::is_none")]
    pub inheritable: Option<bool>,
    #[serde(rename = "configured_value", skip_serializing_if = "Option::is_none")]
    pub configured_value: Option<String>,
    #[serde(rename = "inherited_value", skip_serializing_if = "Option::is_none")]
    pub inherited_value: Option<String>,
    #[serde(rename = "permitted_values", skip_serializing_if = "Option::is_none")]
    pub permitted_values: Option<Vec<String>>,
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

impl ConfigParameterInfo {
    pub fn new() -> ConfigParameterInfo {
        ConfigParameterInfo {
            display_name: None,
            description: None,
            warning: None,
            r#type: None,
            value: None,
            editable: None,
            inheritable: None,
            configured_value: None,
            inherited_value: None,
            permitted_values: None,
            values: None,
        }
    }
}

