/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigUpdateEntryInfo {
    #[serde(rename = "config_key", skip_serializing_if = "Option::is_none")]
    pub config_key: Option<String>,
    #[serde(rename = "old_value", skip_serializing_if = "Option::is_none")]
    pub old_value: Option<String>,
    #[serde(rename = "new_value", skip_serializing_if = "Option::is_none")]
    pub new_value: Option<String>,
}

impl ConfigUpdateEntryInfo {
    pub fn new() -> ConfigUpdateEntryInfo {
        ConfigUpdateEntryInfo {
            config_key: None,
            old_value: None,
            new_value: None,
        }
    }
}

