/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConflictsInfo {
    /// The SHA1 of the commit that was used as the base commit for the Git merge that created the revision. + A base is not set if: + - the merged commits do not have a common ancestor (in this case no_base_reason is NO_COMMON_ANCESTOR).
    #[serde(rename = "base", skip_serializing_if = "Option::is_none")]
    pub base: Option<String>,
    /// The SHA1 of the commit that was used as \"ours\" for the Git merge that created the revision. + - For merge commits that are created by the Create Change REST endpoint \"ours\" is the SHA1 of the change's target branch (the branch that is specified as branch in the ChangeInput).
    #[serde(rename = "ours", skip_serializing_if = "Option::is_none")]
    pub ours: Option<String>,
    /// The SHA1 of the commit that was used as \"theirs\" for the Git merge that created the revision.
    #[serde(rename = "theirs", skip_serializing_if = "Option::is_none")]
    pub theirs: Option<String>,
    /// The merge strategy was used for the Git merge that created the revision. + Possible values: resolve, recursive, simple-two-way-in-core, ours and theirs.
    #[serde(rename = "merge_strategy", skip_serializing_if = "Option::is_none")]
    pub merge_strategy: Option<String>,
    /// Reason why base is not set. + Only set if base is not set. + Possible values are: + - NO_COMMON_ANCESTOR: The merged commits do not have a common ancestor. + - COMPUTED_BASE: The merged commits have multiple merge bases (happens for criss-cross-merges) and the base was computed.
    #[serde(rename = "no_base_reason", skip_serializing_if = "Option::is_none")]
    pub no_base_reason: Option<models::NoMergeBaseReason>,
    /// Whether any of the files in the revision has a conflict due to merging \"ours\" and \"theirs\". + If \"true\" at least one of the files in the revision has a conflict and contains Git conflict markers. The conflicts occurred while performing a merge between \"ours\" and \"theirs\".
    #[serde(rename = "contains_conflicts", skip_serializing_if = "Option::is_none")]
    pub contains_conflicts: Option<bool>,
}

impl ConflictsInfo {
    pub fn new() -> ConflictsInfo {
        ConflictsInfo {
            base: None,
            ours: None,
            theirs: None,
            merge_strategy: None,
            no_base_reason: None,
            contains_conflicts: None,
        }
    }
}

