/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConflictsInfo {
    #[serde(rename = "base", skip_serializing_if = "Option::is_none")]
    pub base: Option<String>,
    #[serde(rename = "ours", skip_serializing_if = "Option::is_none")]
    pub ours: Option<String>,
    #[serde(rename = "theirs", skip_serializing_if = "Option::is_none")]
    pub theirs: Option<String>,
    #[serde(rename = "merge_strategy", skip_serializing_if = "Option::is_none")]
    pub merge_strategy: Option<String>,
    #[serde(rename = "no_base_reason", skip_serializing_if = "Option::is_none")]
    pub no_base_reason: Option<models::NoMergeBaseReason>,
    #[serde(rename = "contains_conflicts", skip_serializing_if = "Option::is_none")]
    pub contains_conflicts: Option<bool>,
}

impl ConflictsInfo {
    pub fn new() -> ConflictsInfo {
        ConflictsInfo {
            base: None,
            ours: None,
            theirs: None,
            merge_strategy: None,
            no_base_reason: None,
            contains_conflicts: None,
        }
    }
}

