/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigInfo {
    /// The description of the project.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// InheritedBooleanInfo that tells whether authors must complete a contributor agreement on the site before pushing any commits or changes to this project.
    #[serde(rename = "use_contributor_agreements", skip_serializing_if = "Option::is_none")]
    pub use_contributor_agreements: Option<Box<models::InheritedBooleanInfo>>,
    /// InheritedBooleanInfo that tells whether Gerrit will try to perform a 3-way merge of text file content when a file has been modified by both the destination branch and the change being submitted. This option only takes effect if submit type is not FAST_FORWARD_ONLY.
    #[serde(rename = "use_content_merge", skip_serializing_if = "Option::is_none")]
    pub use_content_merge: Option<Box<models::InheritedBooleanInfo>>,
    /// InheritedBooleanInfo that tells whether each change must contain a Signed-off-by line from either the author or the uploader in the commit message.
    #[serde(rename = "use_signed_off_by", skip_serializing_if = "Option::is_none")]
    pub use_signed_off_by: Option<Box<models::InheritedBooleanInfo>>,
    /// InheritedBooleanInfo that tells whether a new change is created for every commit not in target branch.
    #[serde(rename = "create_new_change_for_all_not_in_target", skip_serializing_if = "Option::is_none")]
    pub create_new_change_for_all_not_in_target: Option<Box<models::InheritedBooleanInfo>>,
    /// InheritedBooleanInfo that tells whether a valid Change-Id footer in any commit uploaded for review is required. This does not apply to commits pushed directly to a branch or tag. This property is deprecated and will be removed in a future release.
    #[serde(rename = "require_change_id", skip_serializing_if = "Option::is_none")]
    pub require_change_id: Option<Box<models::InheritedBooleanInfo>>,
    /// InheritedBooleanInfo that tells whether signed push validation is enabled on the project.
    #[serde(rename = "enable_signed_push", skip_serializing_if = "Option::is_none")]
    pub enable_signed_push: Option<Box<models::InheritedBooleanInfo>>,
    /// InheritedBooleanInfo that tells whether signed push validation is required on the project.
    #[serde(rename = "require_signed_push", skip_serializing_if = "Option::is_none")]
    pub require_signed_push: Option<Box<models::InheritedBooleanInfo>>,
    /// InheritedBooleanInfo that tells whether implicit merges should be rejected on changes pushed to or submitted in the project.
    #[serde(rename = "reject_implicit_merges", skip_serializing_if = "Option::is_none")]
    pub reject_implicit_merges: Option<Box<models::InheritedBooleanInfo>>,
    /// InheritedBooleanInfo that tells whether all new changes are set as private by default.
    #[serde(rename = "private_by_default", skip_serializing_if = "Option::is_none")]
    pub private_by_default: Option<Box<models::InheritedBooleanInfo>>,
    /// InheritedBooleanInfo that tells whether all new changes are set as work-in-progress by default.
    #[serde(rename = "work_in_progress_by_default", skip_serializing_if = "Option::is_none")]
    pub work_in_progress_by_default: Option<Box<models::InheritedBooleanInfo>>,
    #[serde(rename = "enable_reviewer_by_email", skip_serializing_if = "Option::is_none")]
    pub enable_reviewer_by_email: Option<Box<models::InheritedBooleanInfo>>,
    /// InheritedBooleanInfo that indicates whether a change's author date will be changed to match its submitter date upon submit.
    #[serde(rename = "match_author_to_committer_date", skip_serializing_if = "Option::is_none")]
    pub match_author_to_committer_date: Option<Box<models::InheritedBooleanInfo>>,
    /// InheritedBooleanInfo that tells whether empty commits should be rejected when a change is merged. ActionInfo entities.
    #[serde(rename = "reject_empty_commit", skip_serializing_if = "Option::is_none")]
    pub reject_empty_commit: Option<Box<models::InheritedBooleanInfo>>,
    /// Whether to skip adding the Git commit author and committer as reviewers for a new change.
    #[serde(rename = "skip_adding_author_and_committer_as_reviewers", skip_serializing_if = "Option::is_none")]
    pub skip_adding_author_and_committer_as_reviewers: Option<Box<models::InheritedBooleanInfo>>,
    /// The max object size limit of this project as a MaxObjectSizeLimitInfo entity.
    #[serde(rename = "max_object_size_limit", skip_serializing_if = "Option::is_none")]
    pub max_object_size_limit: Option<Box<models::MaxObjectSizeLimitInfo>>,
    /// Deprecated; equivalent to value in default_submit_type.
    #[serde(rename = "submit_type", skip_serializing_if = "Option::is_none")]
    pub submit_type: Option<models::SubmitType>,
    /// SubmitTypeInfo that describes the default submit type of the project, when not overridden at the change level.
    #[serde(rename = "default_submit_type", skip_serializing_if = "Option::is_none")]
    pub default_submit_type: Option<Box<models::SubmitTypeInfo>>,
    /// The state of the project, can be ACTIVE, READ_ONLY or HIDDEN. + Not set if the project state is ACTIVE.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<models::ProjectState>,
    /// Plugin configuration as map which maps the plugin name to a map of parameter names to ConfigParameterInfo entities. Only filled for users who have read access to refs/meta/config.
    #[serde(rename = "plugin_config", skip_serializing_if = "Option::is_none")]
    pub plugin_config: Option<std::collections::HashMap<String, std::collections::HashMap<String, models::ConfigParameterInfo>>>,
    /// Actions the caller might be able to perform on this project. The information is a map of view names to
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions: Option<std::collections::HashMap<String, models::ActionInfo>>,
    /// Map with the comment link configurations of the project. The name of the comment link configuration is mapped to a CommentlinkInfo entity.
    #[serde(rename = "commentlinks", skip_serializing_if = "Option::is_none")]
    pub commentlinks: Option<std::collections::HashMap<String, models::CommentLinkInfo>>,
    #[serde(rename = "extension_panel_names", skip_serializing_if = "Option::is_none")]
    pub extension_panel_names: Option<std::collections::HashMap<String, Vec<String>>>,
}

impl ConfigInfo {
    pub fn new() -> ConfigInfo {
        ConfigInfo {
            description: None,
            use_contributor_agreements: None,
            use_content_merge: None,
            use_signed_off_by: None,
            create_new_change_for_all_not_in_target: None,
            require_change_id: None,
            enable_signed_push: None,
            require_signed_push: None,
            reject_implicit_merges: None,
            private_by_default: None,
            work_in_progress_by_default: None,
            enable_reviewer_by_email: None,
            match_author_to_committer_date: None,
            reject_empty_commit: None,
            skip_adding_author_and_committer_as_reviewers: None,
            max_object_size_limit: None,
            submit_type: None,
            default_submit_type: None,
            state: None,
            plugin_config: None,
            actions: None,
            commentlinks: None,
            extension_panel_names: None,
        }
    }
}

