/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DateFormat {
    #[serde(rename = "STD")]
    Std,
    #[serde(rename = "US")]
    Us,
    #[serde(rename = "ISO")]
    Iso,
    #[serde(rename = "EURO")]
    Euro,
    #[serde(rename = "UK")]
    Uk,

}

impl std::fmt::Display for DateFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Std => write!(f, "STD"),
            Self::Us => write!(f, "US"),
            Self::Iso => write!(f, "ISO"),
            Self::Euro => write!(f, "EURO"),
            Self::Uk => write!(f, "UK"),
        }
    }
}

impl Default for DateFormat {
    fn default() -> DateFormat {
        Self::Std
    }
}

