/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DefaultBase {
    #[serde(rename = "AUTO_MERGE")]
    AutoMerge,
    #[serde(rename = "FIRST_PARENT")]
    FirstParent,

}

impl std::fmt::Display for DefaultBase {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AutoMerge => write!(f, "AUTO_MERGE"),
            Self::FirstParent => write!(f, "FIRST_PARENT"),
        }
    }
}

impl Default for DefaultBase {
    fn default() -> DefaultBase {
        Self::AutoMerge
    }
}

