/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteCommentInput {
    /// The reason why the comment should be deleted. + If set, the comment's message will be replaced with \"Comment removed by: name; Reason: reason\", or just \"Comment removed by: name.\" if not set.
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl DeleteCommentInput {
    pub fn new() -> DeleteCommentInput {
        DeleteCommentInput {
            reason: None,
        }
    }
}

