/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeletedDraftCommentInfo {
    /// ChangeInfo entity describing the change on which one or more comments was deleted. Populated with no change list options.
    #[serde(rename = "change", skip_serializing_if = "Option::is_none")]
    pub change: Option<Box<models::ChangeInfo>>,
    /// List of CommentInfo entities for each comment that was deleted.
    #[serde(rename = "deleted", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<Vec<models::CommentInfo>>,
}

impl DeletedDraftCommentInfo {
    pub fn new() -> DeletedDraftCommentInfo {
        DeletedDraftCommentInfo {
            change: None,
            deleted: None,
        }
    }
}

