/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteVoteInput {
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "notify", skip_serializing_if = "Option::is_none")]
    pub notify: Option<models::NotifyHandling>,
    #[serde(rename = "notify_details", skip_serializing_if = "Option::is_none")]
    pub notify_details: Option<std::collections::HashMap<String, models::NotifyInfo>>,
    #[serde(rename = "ignore_automatic_attention_set_rules", skip_serializing_if = "Option::is_none")]
    pub ignore_automatic_attention_set_rules: Option<bool>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl DeleteVoteInput {
    pub fn new() -> DeleteVoteInput {
        DeleteVoteInput {
            label: None,
            notify: None,
            notify_details: None,
            ignore_automatic_attention_set_rules: None,
            reason: None,
        }
    }
}

