/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadSchemeInfo {
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "is_auth_required", skip_serializing_if = "Option::is_none")]
    pub is_auth_required: Option<bool>,
    #[serde(rename = "is_auth_supported", skip_serializing_if = "Option::is_none")]
    pub is_auth_supported: Option<bool>,
    #[serde(rename = "commands", skip_serializing_if = "Option::is_none")]
    pub commands: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "clone_commands", skip_serializing_if = "Option::is_none")]
    pub clone_commands: Option<std::collections::HashMap<String, String>>,
}

impl DownloadSchemeInfo {
    pub fn new() -> DownloadSchemeInfo {
        DownloadSchemeInfo {
            url: None,
            description: None,
            is_auth_required: None,
            is_auth_supported: None,
            commands: None,
            clone_commands: None,
        }
    }
}

