/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DraftInput {
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    #[serde(rename = "unresolved", skip_serializing_if = "Option::is_none")]
    pub unresolved: Option<bool>,
    #[serde(rename = "patch_set", skip_serializing_if = "Option::is_none")]
    pub patch_set: Option<i32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "side", skip_serializing_if = "Option::is_none")]
    pub side: Option<models::Side>,
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<i32>,
    #[serde(rename = "line", skip_serializing_if = "Option::is_none")]
    pub line: Option<i32>,
    #[serde(rename = "range", skip_serializing_if = "Option::is_none")]
    pub range: Option<Box<models::Range>>,
    #[serde(rename = "in_reply_to", skip_serializing_if = "Option::is_none")]
    pub in_reply_to: Option<String>,
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "commit_id", skip_serializing_if = "Option::is_none")]
    pub commit_id: Option<String>,
    #[serde(rename = "fix_suggestions", skip_serializing_if = "Option::is_none")]
    pub fix_suggestions: Option<Vec<models::FixSuggestionInfo>>,
    #[serde(rename = "is_ai", skip_serializing_if = "Option::is_none")]
    pub is_ai: Option<bool>,
}

impl DraftInput {
    pub fn new() -> DraftInput {
        DraftInput {
            tag: None,
            unresolved: None,
            patch_set: None,
            id: None,
            path: None,
            side: None,
            parent: None,
            line: None,
            range: None,
            in_reply_to: None,
            updated: None,
            message: None,
            commit_id: None,
            fix_suggestions: None,
            is_ai: None,
        }
    }
}

