/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DraftHandling {
    #[serde(rename = "KEEP")]
    Keep,
    #[serde(rename = "PUBLISH")]
    Publish,
    #[serde(rename = "PUBLISH_ALL_REVISIONS")]
    PublishAllRevisions,

}

impl std::fmt::Display for DraftHandling {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Keep => write!(f, "KEEP"),
            Self::Publish => write!(f, "PUBLISH"),
            Self::PublishAllRevisions => write!(f, "PUBLISH_ALL_REVISIONS"),
        }
    }
}

impl Default for DraftHandling {
    fn default() -> DraftHandling {
        Self::Keep
    }
}

