/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditInfo {
    #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
    pub commit: Option<Box<models::CommitInfo>>,
    #[serde(rename = "base_patch_set_number", skip_serializing_if = "Option::is_none")]
    pub base_patch_set_number: Option<i32>,
    #[serde(rename = "base_revision", skip_serializing_if = "Option::is_none")]
    pub base_revision: Option<String>,
    #[serde(rename = "ref", skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
    #[serde(rename = "fetch", skip_serializing_if = "Option::is_none")]
    pub fetch: Option<std::collections::HashMap<String, models::FetchInfo>>,
    #[serde(rename = "files", skip_serializing_if = "Option::is_none")]
    pub files: Option<std::collections::HashMap<String, models::CommonFileInfo>>,
    #[serde(rename = "contains_git_conflicts", skip_serializing_if = "Option::is_none")]
    pub contains_git_conflicts: Option<bool>,
}

impl EditInfo {
    pub fn new() -> EditInfo {
        EditInfo {
            commit: None,
            base_patch_set_number: None,
            base_revision: None,
            r#ref: None,
            fetch: None,
            files: None,
            contains_git_conflicts: None,
        }
    }
}

