/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntriesInfo {
    #[serde(rename = "mem", skip_serializing_if = "Option::is_none")]
    pub mem: Option<i32>,
    #[serde(rename = "disk", skip_serializing_if = "Option::is_none")]
    pub disk: Option<i32>,
    #[serde(rename = "space", skip_serializing_if = "Option::is_none")]
    pub space: Option<String>,
}

impl EntriesInfo {
    pub fn new() -> EntriesInfo {
        EntriesInfo {
            mem: None,
            disk: None,
            space: None,
        }
    }
}

