/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileChange {
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "file_mode", skip_serializing_if = "Option::is_none")]
    pub file_mode: Option<i32>,
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<bool>,
    #[serde(rename = "rename_from", skip_serializing_if = "Option::is_none")]
    pub rename_from: Option<String>,
}

impl FileChange {
    pub fn new() -> FileChange {
        FileChange {
            content: None,
            file_mode: None,
            delete: None,
            rename_from: None,
        }
    }
}

