/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileMeta {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "content_type", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    #[serde(rename = "lines", skip_serializing_if = "Option::is_none")]
    pub lines: Option<i32>,
    #[serde(rename = "web_links", skip_serializing_if = "Option::is_none")]
    pub web_links: Option<Vec<models::WebLinkInfo>>,
}

impl FileMeta {
    pub fn new() -> FileMeta {
        FileMeta {
            name: None,
            content_type: None,
            lines: None,
            web_links: None,
        }
    }
}

