/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FixReplacementInfo {
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "range", skip_serializing_if = "Option::is_none")]
    pub range: Option<Box<models::Range>>,
    #[serde(rename = "replacement", skip_serializing_if = "Option::is_none")]
    pub replacement: Option<String>,
}

impl FixReplacementInfo {
    pub fn new() -> FixReplacementInfo {
        FixReplacementInfo {
            path: None,
            range: None,
            replacement: None,
        }
    }
}

