/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FixInput {
    #[serde(rename = "delete_patch_set_if_commit_missing", skip_serializing_if = "Option::is_none")]
    pub delete_patch_set_if_commit_missing: Option<bool>,
    #[serde(rename = "expect_merged_as", skip_serializing_if = "Option::is_none")]
    pub expect_merged_as: Option<String>,
}

impl FixInput {
    pub fn new() -> FixInput {
        FixInput {
            delete_patch_set_if_commit_missing: None,
            expect_merged_as: None,
        }
    }
}

