/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlowInfo {
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<Box<models::AccountInfo>>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "stages", skip_serializing_if = "Option::is_none")]
    pub stages: Option<Vec<models::FlowStageInfo>>,
    #[serde(rename = "last_evaluated", skip_serializing_if = "Option::is_none")]
    pub last_evaluated: Option<String>,
}

impl FlowInfo {
    pub fn new() -> FlowInfo {
        FlowInfo {
            uuid: None,
            owner: None,
            created: None,
            stages: None,
            last_evaluated: None,
        }
    }
}

