/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlowStageInfo {
    /// The expression defining the condition and the action of this stage as a FlowExpressionInfo entity.
    #[serde(rename = "expression", skip_serializing_if = "Option::is_none")]
    pub expression: Option<Box<models::FlowExpressionInfo>>,
    /// The state for this stage. Can be PENDING (the condition of the stage is not satisfied yet or the action has not been executed yet), DONE (the condition of the stage is satisfied and the action has been executed), FAILED (the stage has a non-recoverable error, e.g.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<models::FlowStageState>,
    /// Optional message for the stage.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl FlowStageInfo {
    pub fn new() -> FlowStageInfo {
        FlowStageInfo {
            expression: None,
            state: None,
            message: None,
        }
    }
}

