/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GerritInfo {
    #[serde(rename = "all_projects", skip_serializing_if = "Option::is_none")]
    pub all_projects: Option<String>,
    #[serde(rename = "all_users", skip_serializing_if = "Option::is_none")]
    pub all_users: Option<String>,
    #[serde(rename = "doc_search", skip_serializing_if = "Option::is_none")]
    pub doc_search: Option<bool>,
    #[serde(rename = "doc_url", skip_serializing_if = "Option::is_none")]
    pub doc_url: Option<String>,
    #[serde(rename = "edit_gpg_keys", skip_serializing_if = "Option::is_none")]
    pub edit_gpg_keys: Option<bool>,
    #[serde(rename = "report_bug_url", skip_serializing_if = "Option::is_none")]
    pub report_bug_url: Option<String>,
    #[serde(rename = "primary_weblink_name", skip_serializing_if = "Option::is_none")]
    pub primary_weblink_name: Option<String>,
    #[serde(rename = "instance_id", skip_serializing_if = "Option::is_none")]
    pub instance_id: Option<String>,
    #[serde(rename = "default_branch", skip_serializing_if = "Option::is_none")]
    pub default_branch: Option<String>,
    #[serde(rename = "project_state_predicate_enabled", skip_serializing_if = "Option::is_none")]
    pub project_state_predicate_enabled: Option<bool>,
}

impl GerritInfo {
    pub fn new() -> GerritInfo {
        GerritInfo {
            all_projects: None,
            all_users: None,
            doc_search: None,
            doc_url: None,
            edit_gpg_keys: None,
            report_bug_url: None,
            primary_weblink_name: None,
            instance_id: None,
            default_branch: None,
            project_state_predicate_enabled: None,
        }
    }
}

