/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetConfigServerIndexes200ResponseInnerVersionsValue {
    #[serde(rename = "is_write", skip_serializing_if = "Option::is_none")]
    pub is_write: Option<bool>,
    #[serde(rename = "is_search", skip_serializing_if = "Option::is_none")]
    pub is_search: Option<bool>,
    #[serde(rename = "num_docs", skip_serializing_if = "Option::is_none")]
    pub num_docs: Option<i32>,
}

impl GetConfigServerIndexes200ResponseInnerVersionsValue {
    pub fn new() -> GetConfigServerIndexes200ResponseInnerVersionsValue {
        GetConfigServerIndexes200ResponseInnerVersionsValue {
            is_write: None,
            is_search: None,
            num_docs: None,
        }
    }
}

