/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetConfigServerCaches200Response {
    Object(std::collections::HashMap<String, models::CacheInfo>),
    ArrayVecString(Vec<String>),
}

impl Default for GetConfigServerCaches200Response {
    fn default() -> Self {
        Self::Object(Default::default())
    }
}

