/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetConfigServerVersion200ResponseOneOf {
    #[serde(rename = "gerrit_version", skip_serializing_if = "Option::is_none")]
    pub gerrit_version: Option<String>,
    #[serde(rename = "note_db_version", skip_serializing_if = "Option::is_none")]
    pub note_db_version: Option<i32>,
    #[serde(rename = "change_index_version", skip_serializing_if = "Option::is_none")]
    pub change_index_version: Option<i32>,
    #[serde(rename = "account_index_version", skip_serializing_if = "Option::is_none")]
    pub account_index_version: Option<i32>,
    #[serde(rename = "project_index_version", skip_serializing_if = "Option::is_none")]
    pub project_index_version: Option<i32>,
    #[serde(rename = "group_index_version", skip_serializing_if = "Option::is_none")]
    pub group_index_version: Option<i32>,
}

impl GetConfigServerVersion200ResponseOneOf {
    pub fn new() -> GetConfigServerVersion200ResponseOneOf {
        GetConfigServerVersion200ResponseOneOf {
            gerrit_version: None,
            note_db_version: None,
            change_index_version: None,
            account_index_version: None,
            project_index_version: None,
            group_index_version: None,
        }
    }
}

