/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitPerson {
    /// The name of the author/committer.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The email address of the author/committer.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The timestamp of when this identity was constructed.
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// The timezone offset from UTC of when this identity was constructed.
    #[serde(rename = "tz", skip_serializing_if = "Option::is_none")]
    pub tz: Option<i32>,
}

impl GitPerson {
    pub fn new() -> GitPerson {
        GitPerson {
            name: None,
            email: None,
            date: None,
            tz: None,
        }
    }
}

