/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HttpPasswordInput {
    #[serde(rename = "http_password", skip_serializing_if = "Option::is_none")]
    pub http_password: Option<String>,
    #[serde(rename = "generate", skip_serializing_if = "Option::is_none")]
    pub generate: Option<bool>,
}

impl HttpPasswordInput {
    pub fn new() -> HttpPasswordInput {
        HttpPasswordInput {
            http_password: None,
            generate: None,
        }
    }
}

