/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IncludedInInfo {
    /// The list of branches this change was merged into. Each branch is listed without the 'refs/head/' prefix.
    #[serde(rename = "branches", skip_serializing_if = "Option::is_none")]
    pub branches: Option<Vec<String>>,
    /// The list of tags this change was tagged with. Each tag is listed without the 'refs/tags/' prefix.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// A map that maps a name to a list of external systems that include this change, e.g. a list of servers on which this change is deployed.
    #[serde(rename = "external", skip_serializing_if = "Option::is_none")]
    pub external: Option<std::collections::HashMap<String, Vec<String>>>,
}

impl IncludedInInfo {
    pub fn new() -> IncludedInInfo {
        IncludedInInfo {
            branches: None,
            tags: None,
            external: None,
        }
    }
}

