/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexProjectInput {
    #[serde(rename = "index_children", skip_serializing_if = "Option::is_none")]
    pub index_children: Option<bool>,
    #[serde(rename = "async", skip_serializing_if = "Option::is_none")]
    pub r#async: Option<bool>,
}

impl IndexProjectInput {
    pub fn new() -> IndexProjectInput {
        IndexProjectInput {
            index_children: None,
            r#async: None,
        }
    }
}

