/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexChangesInput {
    #[serde(rename = "changes", skip_serializing_if = "Option::is_none")]
    pub changes: Option<Vec<String>>,
    #[serde(rename = "delete_missing", skip_serializing_if = "Option::is_none")]
    pub delete_missing: Option<bool>,
}

impl IndexChangesInput {
    pub fn new() -> IndexChangesInput {
        IndexChangesInput {
            changes: None,
            delete_missing: None,
        }
    }
}

