/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InheritableBoolean {
    #[serde(rename = "TRUE")]
    True,
    #[serde(rename = "FALSE")]
    False,
    #[serde(rename = "INHERIT")]
    Inherit,

}

impl std::fmt::Display for InheritableBoolean {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::True => write!(f, "TRUE"),
            Self::False => write!(f, "FALSE"),
            Self::Inherit => write!(f, "INHERIT"),
        }
    }
}

impl Default for InheritableBoolean {
    fn default() -> InheritableBoolean {
        Self::True
    }
}

