/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IntraLineStatus {
    #[serde(rename = "OK")]
    Ok,
    #[serde(rename = "TIMEOUT")]
    Timeout,
    #[serde(rename = "FAILURE")]
    Failure,

}

impl std::fmt::Display for IntraLineStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ok => write!(f, "OK"),
            Self::Timeout => write!(f, "TIMEOUT"),
            Self::Failure => write!(f, "FAILURE"),
        }
    }
}

impl Default for IntraLineStatus {
    fn default() -> IntraLineStatus {
        Self::Ok
    }
}

