/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LabelDefinitionInput {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "function", skip_serializing_if = "Option::is_none")]
    pub function: Option<String>,
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "default_value", skip_serializing_if = "Option::is_none")]
    pub default_value: Option<i32>,
    #[serde(rename = "branches", skip_serializing_if = "Option::is_none")]
    pub branches: Option<Vec<String>>,
    #[serde(rename = "can_override", skip_serializing_if = "Option::is_none")]
    pub can_override: Option<bool>,
    #[serde(rename = "copy_condition", skip_serializing_if = "Option::is_none")]
    pub copy_condition: Option<String>,
    #[serde(rename = "unset_copy_condition", skip_serializing_if = "Option::is_none")]
    pub unset_copy_condition: Option<bool>,
    #[serde(rename = "allow_post_submit", skip_serializing_if = "Option::is_none")]
    pub allow_post_submit: Option<bool>,
    #[serde(rename = "ignore_self_approval", skip_serializing_if = "Option::is_none")]
    pub ignore_self_approval: Option<bool>,
    #[serde(rename = "commit_message", skip_serializing_if = "Option::is_none")]
    pub commit_message: Option<String>,
}

impl LabelDefinitionInput {
    pub fn new() -> LabelDefinitionInput {
        LabelDefinitionInput {
            name: None,
            description: None,
            function: None,
            values: None,
            default_value: None,
            branches: None,
            can_override: None,
            copy_condition: None,
            unset_copy_condition: None,
            allow_post_submit: None,
            ignore_self_approval: None,
            commit_message: None,
        }
    }
}

