/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LabelInfo {
    #[serde(rename = "approved", skip_serializing_if = "Option::is_none")]
    pub approved: Option<Box<models::AccountInfo>>,
    #[serde(rename = "rejected", skip_serializing_if = "Option::is_none")]
    pub rejected: Option<Box<models::AccountInfo>>,
    #[serde(rename = "recommended", skip_serializing_if = "Option::is_none")]
    pub recommended: Option<Box<models::AccountInfo>>,
    #[serde(rename = "disliked", skip_serializing_if = "Option::is_none")]
    pub disliked: Option<Box<models::AccountInfo>>,
    #[serde(rename = "all", skip_serializing_if = "Option::is_none")]
    pub all: Option<Vec<models::ApprovalInfo>>,
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<i32>,
    #[serde(rename = "default_value", skip_serializing_if = "Option::is_none")]
    pub default_value: Option<i32>,
    #[serde(rename = "optional", skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
    #[serde(rename = "blocking", skip_serializing_if = "Option::is_none")]
    pub blocking: Option<bool>,
}

impl LabelInfo {
    pub fn new() -> LabelInfo {
        LabelInfo {
            approved: None,
            rejected: None,
            recommended: None,
            disliked: None,
            all: None,
            values: None,
            description: None,
            value: None,
            default_value: None,
            optional: None,
            blocking: None,
        }
    }
}

