/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LabelInfo {
    /// One user who approved this label on the change (voted the maximum value) as an AccountInfo entity.
    #[serde(rename = "approved", skip_serializing_if = "Option::is_none")]
    pub approved: Option<Box<models::AccountInfo>>,
    /// One user who rejected this label on the change (voted the minimum value) as an AccountInfo entity.
    #[serde(rename = "rejected", skip_serializing_if = "Option::is_none")]
    pub rejected: Option<Box<models::AccountInfo>>,
    /// One user who recommended this label on the change (voted positively, but not the maximum value) as an AccountInfo entity.
    #[serde(rename = "recommended", skip_serializing_if = "Option::is_none")]
    pub recommended: Option<Box<models::AccountInfo>>,
    /// One user who disliked this label on the change (voted negatively, but not the minimum value) as an AccountInfo entity.
    #[serde(rename = "disliked", skip_serializing_if = "Option::is_none")]
    pub disliked: Option<Box<models::AccountInfo>>,
    /// List of all approvals for this label as a list of ApprovalInfo entities. Items in this list may not represent actual votes cast by users; if a user votes on any label, a corresponding ApprovalInfo will appear in this list for all labels.
    #[serde(rename = "all", skip_serializing_if = "Option::is_none")]
    pub all: Option<Vec<models::ApprovalInfo>>,
    /// A map of all values that are allowed for this label. The map maps the values (\"-2\", \"-1\", \" 0\", \"+1\", \"+2\") to the value descriptions.
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<std::collections::HashMap<String, String>>,
    /// The description of the label.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The voting value of the user who recommended/disliked this label on the change if it is not \"+1\"/\"-1\".
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<i32>,
    /// The default voting value for the label. This value may be outside the range specified in permitted_labels.
    #[serde(rename = "default_value", skip_serializing_if = "Option::is_none")]
    pub default_value: Option<i32>,
    /// Whether the label is optional. Optional means the label may be set, but it's neither necessary for submission nor does it block submission if set.
    #[serde(rename = "optional", skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
    /// If true, the label blocks submit operation. If not set, the default is false.
    #[serde(rename = "blocking", skip_serializing_if = "Option::is_none")]
    pub blocking: Option<bool>,
}

impl LabelInfo {
    pub fn new() -> LabelInfo {
        LabelInfo {
            approved: None,
            rejected: None,
            recommended: None,
            disliked: None,
            all: None,
            values: None,
            description: None,
            value: None,
            default_value: None,
            optional: None,
            blocking: None,
        }
    }
}

