/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LabelStatus {
    #[serde(rename = "OK")]
    Ok,
    #[serde(rename = "REJECT")]
    Reject,
    #[serde(rename = "NEED")]
    Need,
    #[serde(rename = "MAY")]
    May,
    #[serde(rename = "IMPOSSIBLE")]
    Impossible,

}

impl std::fmt::Display for LabelStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ok => write!(f, "OK"),
            Self::Reject => write!(f, "REJECT"),
            Self::Need => write!(f, "NEED"),
            Self::May => write!(f, "MAY"),
            Self::Impossible => write!(f, "IMPOSSIBLE"),
        }
    }
}

impl Default for LabelStatus {
    fn default() -> LabelStatus {
        Self::Ok
    }
}

