/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LegacySubmitRequirementInfo {
    /// The status of the submit requirement, for example OK or NOT_READY.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// A human readable description of the submit requirement.
    #[serde(rename = "fallback_text", skip_serializing_if = "Option::is_none")]
    pub fallback_text: Option<String>,
    /// The type of the submit requirement.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl LegacySubmitRequirementInfo {
    pub fn new() -> LegacySubmitRequirementInfo {
        LegacySubmitRequirementInfo {
            status: None,
            fallback_text: None,
            r#type: None,
        }
    }
}

