/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ListChangesOption {
    #[serde(rename = "LABELS")]
    Labels,
    #[serde(rename = "DETAILED_LABELS")]
    DetailedLabels,
    #[serde(rename = "CURRENT_REVISION")]
    CurrentRevision,
    #[serde(rename = "ALL_REVISIONS")]
    AllRevisions,
    #[serde(rename = "CURRENT_COMMIT")]
    CurrentCommit,
    #[serde(rename = "ALL_COMMITS")]
    AllCommits,
    #[serde(rename = "CURRENT_FILES")]
    CurrentFiles,
    #[serde(rename = "ALL_FILES")]
    AllFiles,
    #[serde(rename = "DETAILED_ACCOUNTS")]
    DetailedAccounts,
    #[serde(rename = "MESSAGES")]
    Messages,
    #[serde(rename = "CURRENT_ACTIONS")]
    CurrentActions,
    #[serde(rename = "REVIEWED")]
    Reviewed,
    #[serde(rename = "DRAFT_COMMENTS")]
    DraftComments,
    #[serde(rename = "DOWNLOAD_COMMANDS")]
    DownloadCommands,
    #[serde(rename = "WEB_LINKS")]
    WebLinks,
    #[serde(rename = "CHECK")]
    Check,
    #[serde(rename = "CHANGE_ACTIONS")]
    ChangeActions,
    #[serde(rename = "COMMIT_FOOTERS")]
    CommitFooters,
    #[serde(rename = "PUSH_CERTIFICATES")]
    PushCertificates,
    #[serde(rename = "REVIEWER_UPDATES")]
    ReviewerUpdates,
    #[serde(rename = "SUBMITTABLE")]
    Submittable,
    #[serde(rename = "TRACKING_IDS")]
    TrackingIds,
    #[serde(rename = "SKIP_MERGEABLE")]
    SkipMergeable,
    #[serde(rename = "SKIP_DIFFSTAT")]
    SkipDiffstat,
    #[serde(rename = "SUBMIT_REQUIREMENTS")]
    SubmitRequirements,
    #[serde(rename = "CUSTOM_KEYED_VALUES")]
    CustomKeyedValues,
    #[serde(rename = "STAR")]
    Star,
    #[serde(rename = "PARENTS")]
    Parents,

}

impl std::fmt::Display for ListChangesOption {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Labels => write!(f, "LABELS"),
            Self::DetailedLabels => write!(f, "DETAILED_LABELS"),
            Self::CurrentRevision => write!(f, "CURRENT_REVISION"),
            Self::AllRevisions => write!(f, "ALL_REVISIONS"),
            Self::CurrentCommit => write!(f, "CURRENT_COMMIT"),
            Self::AllCommits => write!(f, "ALL_COMMITS"),
            Self::CurrentFiles => write!(f, "CURRENT_FILES"),
            Self::AllFiles => write!(f, "ALL_FILES"),
            Self::DetailedAccounts => write!(f, "DETAILED_ACCOUNTS"),
            Self::Messages => write!(f, "MESSAGES"),
            Self::CurrentActions => write!(f, "CURRENT_ACTIONS"),
            Self::Reviewed => write!(f, "REVIEWED"),
            Self::DraftComments => write!(f, "DRAFT_COMMENTS"),
            Self::DownloadCommands => write!(f, "DOWNLOAD_COMMANDS"),
            Self::WebLinks => write!(f, "WEB_LINKS"),
            Self::Check => write!(f, "CHECK"),
            Self::ChangeActions => write!(f, "CHANGE_ACTIONS"),
            Self::CommitFooters => write!(f, "COMMIT_FOOTERS"),
            Self::PushCertificates => write!(f, "PUSH_CERTIFICATES"),
            Self::ReviewerUpdates => write!(f, "REVIEWER_UPDATES"),
            Self::Submittable => write!(f, "SUBMITTABLE"),
            Self::TrackingIds => write!(f, "TRACKING_IDS"),
            Self::SkipMergeable => write!(f, "SKIP_MERGEABLE"),
            Self::SkipDiffstat => write!(f, "SKIP_DIFFSTAT"),
            Self::SubmitRequirements => write!(f, "SUBMIT_REQUIREMENTS"),
            Self::CustomKeyedValues => write!(f, "CUSTOM_KEYED_VALUES"),
            Self::Star => write!(f, "STAR"),
            Self::Parents => write!(f, "PARENTS"),
        }
    }
}

impl Default for ListChangesOption {
    fn default() -> ListChangesOption {
        Self::Labels
    }
}

