/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MemSummaryInfo {
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<String>,
    #[serde(rename = "used", skip_serializing_if = "Option::is_none")]
    pub used: Option<String>,
    #[serde(rename = "free", skip_serializing_if = "Option::is_none")]
    pub free: Option<String>,
    #[serde(rename = "buffers", skip_serializing_if = "Option::is_none")]
    pub buffers: Option<String>,
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<String>,
    #[serde(rename = "open_files", skip_serializing_if = "Option::is_none")]
    pub open_files: Option<i32>,
}

impl MemSummaryInfo {
    pub fn new() -> MemSummaryInfo {
        MemSummaryInfo {
            total: None,
            used: None,
            free: None,
            buffers: None,
            max: None,
            open_files: None,
        }
    }
}

