/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MergeableInfo {
    #[serde(rename = "submit_type", skip_serializing_if = "Option::is_none")]
    pub submit_type: Option<models::SubmitType>,
    #[serde(rename = "strategy", skip_serializing_if = "Option::is_none")]
    pub strategy: Option<String>,
    #[serde(rename = "mergeable", skip_serializing_if = "Option::is_none")]
    pub mergeable: Option<bool>,
    #[serde(rename = "commit_merged", skip_serializing_if = "Option::is_none")]
    pub commit_merged: Option<bool>,
    #[serde(rename = "content_merged", skip_serializing_if = "Option::is_none")]
    pub content_merged: Option<bool>,
    #[serde(rename = "conflicts", skip_serializing_if = "Option::is_none")]
    pub conflicts: Option<Vec<String>>,
    #[serde(rename = "mergeable_into", skip_serializing_if = "Option::is_none")]
    pub mergeable_into: Option<Vec<String>>,
}

impl MergeableInfo {
    pub fn new() -> MergeableInfo {
        MergeableInfo {
            submit_type: None,
            strategy: None,
            mergeable: None,
            commit_merged: None,
            content_merged: None,
            conflicts: None,
            mergeable_into: None,
        }
    }
}

