/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MigrateLabelsInfo {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::SchemaMigrateLabelFunctionsToSubmitRequirementStatus>,
}

impl MigrateLabelsInfo {
    pub fn new() -> MigrateLabelsInfo {
        MigrateLabelsInfo {
            status: None,
        }
    }
}

