/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MigrateLabelFunctionsToSubmitRequirementStatus {
    #[serde(rename = "MIGRATED")]
    Migrated,
    #[serde(rename = "HAS_PROLOG")]
    HasProlog,
    #[serde(rename = "PREVIOUSLY_MIGRATED")]
    PreviouslyMigrated,
    #[serde(rename = "NO_CHANGE")]
    NoChange,

}

impl std::fmt::Display for MigrateLabelFunctionsToSubmitRequirementStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Migrated => write!(f, "MIGRATED"),
            Self::HasProlog => write!(f, "HAS_PROLOG"),
            Self::PreviouslyMigrated => write!(f, "PREVIOUSLY_MIGRATED"),
            Self::NoChange => write!(f, "NO_CHANGE"),
        }
    }
}

impl Default for MigrateLabelFunctionsToSubmitRequirementStatus {
    fn default() -> MigrateLabelFunctionsToSubmitRequirementStatus {
        Self::Migrated
    }
}

