/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MigrateLabelsReviewInfo {
    /// The status of the migration. Takes one of the following values: MIGRATED, HAS_PROLOG, PREVIOUSLY_MIGRATED, NO_CHANGE
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::MigrateLabelFunctionsToSubmitRequirementStatus>,
    /// The change created. It is a ChangeInfo entity and is set only when the status value is MIGRATED.
    #[serde(rename = "change", skip_serializing_if = "Option::is_none")]
    pub change: Option<Box<models::ChangeInfo>>,
}

impl MigrateLabelsReviewInfo {
    pub fn new() -> MigrateLabelsReviewInfo {
        MigrateLabelsReviewInfo {
            status: None,
            change: None,
        }
    }
}

