/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MoveInput {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "destination_branch", skip_serializing_if = "Option::is_none")]
    pub destination_branch: Option<String>,
    #[serde(rename = "keep_all_votes", skip_serializing_if = "Option::is_none")]
    pub keep_all_votes: Option<bool>,
}

impl MoveInput {
    pub fn new() -> MoveInput {
        MoveInput {
            message: None,
            destination_branch: None,
            keep_all_votes: None,
        }
    }
}

