/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NoMergeBaseReason {
    #[serde(rename = "HISTORIC_DATA_WITHOUT_BASE")]
    HistoricDataWithoutBase,
    #[serde(rename = "NO_COMMON_ANCESTOR")]
    NoCommonAncestor,
    #[serde(rename = "COMPUTED_BASE")]
    ComputedBase,
    #[serde(rename = "ONE_SIDED_MERGE_STRATEGY")]
    OneSidedMergeStrategy,
    #[serde(rename = "NO_MERGE_PERFORMED")]
    NoMergePerformed,

}

impl std::fmt::Display for NoMergeBaseReason {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::HistoricDataWithoutBase => write!(f, "HISTORIC_DATA_WITHOUT_BASE"),
            Self::NoCommonAncestor => write!(f, "NO_COMMON_ANCESTOR"),
            Self::ComputedBase => write!(f, "COMPUTED_BASE"),
            Self::OneSidedMergeStrategy => write!(f, "ONE_SIDED_MERGE_STRATEGY"),
            Self::NoMergePerformed => write!(f, "NO_MERGE_PERFORMED"),
        }
    }
}

impl Default for NoMergeBaseReason {
    fn default() -> NoMergeBaseReason {
        Self::HistoricDataWithoutBase
    }
}

