/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParentInfo {
    #[serde(rename = "branch_name", skip_serializing_if = "Option::is_none")]
    pub branch_name: Option<String>,
    #[serde(rename = "commit_id", skip_serializing_if = "Option::is_none")]
    pub commit_id: Option<String>,
    #[serde(rename = "is_merged_in_target_branch", skip_serializing_if = "Option::is_none")]
    pub is_merged_in_target_branch: Option<bool>,
    #[serde(rename = "change_id", skip_serializing_if = "Option::is_none")]
    pub change_id: Option<String>,
    #[serde(rename = "change_number", skip_serializing_if = "Option::is_none")]
    pub change_number: Option<i32>,
    #[serde(rename = "patch_set_number", skip_serializing_if = "Option::is_none")]
    pub patch_set_number: Option<i32>,
    #[serde(rename = "change_status", skip_serializing_if = "Option::is_none")]
    pub change_status: Option<String>,
}

impl ParentInfo {
    pub fn new() -> ParentInfo {
        ParentInfo {
            branch_name: None,
            commit_id: None,
            is_merged_in_target_branch: None,
            change_id: None,
            change_number: None,
            patch_set_number: None,
            change_status: None,
        }
    }
}

