/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectAccessInfo {
    #[serde(rename = "revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    #[serde(rename = "inherits_from", skip_serializing_if = "Option::is_none")]
    pub inherits_from: Option<Box<models::ProjectInfo>>,
    #[serde(rename = "local", skip_serializing_if = "Option::is_none")]
    pub local: Option<std::collections::HashMap<String, models::AccessSectionInfo>>,
    #[serde(rename = "is_owner", skip_serializing_if = "Option::is_none")]
    pub is_owner: Option<bool>,
    #[serde(rename = "owner_of", skip_serializing_if = "Option::is_none")]
    pub owner_of: Option<Vec<String>>,
    #[serde(rename = "can_upload", skip_serializing_if = "Option::is_none")]
    pub can_upload: Option<bool>,
    #[serde(rename = "can_add", skip_serializing_if = "Option::is_none")]
    pub can_add: Option<bool>,
    #[serde(rename = "can_add_tags", skip_serializing_if = "Option::is_none")]
    pub can_add_tags: Option<bool>,
    #[serde(rename = "config_visible", skip_serializing_if = "Option::is_none")]
    pub config_visible: Option<bool>,
    #[serde(rename = "require_change_for_config_update", skip_serializing_if = "Option::is_none")]
    pub require_change_for_config_update: Option<bool>,
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<std::collections::HashMap<String, models::GroupInfo>>,
    #[serde(rename = "config_web_links", skip_serializing_if = "Option::is_none")]
    pub config_web_links: Option<Vec<models::WebLinkInfo>>,
}

impl ProjectAccessInfo {
    pub fn new() -> ProjectAccessInfo {
        ProjectAccessInfo {
            revision: None,
            inherits_from: None,
            local: None,
            is_owner: None,
            owner_of: None,
            can_upload: None,
            can_add: None,
            can_add_tags: None,
            config_visible: None,
            require_change_for_config_update: None,
            groups: None,
            config_web_links: None,
        }
    }
}

