/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProjectConfigEntryType {
    #[serde(rename = "STRING")]
    String,
    #[serde(rename = "INT")]
    Int,
    #[serde(rename = "LONG")]
    Long,
    #[serde(rename = "BOOLEAN")]
    Boolean,
    #[serde(rename = "LIST")]
    List,
    #[serde(rename = "ARRAY")]
    Array,

}

impl std::fmt::Display for ProjectConfigEntryType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::String => write!(f, "STRING"),
            Self::Int => write!(f, "INT"),
            Self::Long => write!(f, "LONG"),
            Self::Boolean => write!(f, "BOOLEAN"),
            Self::List => write!(f, "LIST"),
            Self::Array => write!(f, "ARRAY"),
        }
    }
}

impl Default for ProjectConfigEntryType {
    fn default() -> ProjectConfigEntryType {
        Self::String
    }
}

