/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RebaseInput {
    /// The new parent revision. This can be a ref or a SHA-1 to a concrete patchset. + Alternatively, a change number can be specified, in which case the current patch set is inferred.
    #[serde(rename = "base", skip_serializing_if = "Option::is_none")]
    pub base: Option<String>,
    /// The strategy of the merge, can be recursive, resolve, simple-two-way-in-core, ours or theirs, default will use project settings.
    #[serde(rename = "strategy", skip_serializing_if = "Option::is_none")]
    pub strategy: Option<String>,
    /// If true, the rebase also succeeds if there are conflicts. + If there are conflicts the file contents of the rebased patch set contain git conflict markers to indicate the conflicts.
    #[serde(rename = "allow_conflicts", skip_serializing_if = "Option::is_none")]
    pub allow_conflicts: Option<bool>,
    /// If true, the rebase is done on behalf of the uploader. + This means the uploader of the current patch set will also be the uploader of the rebased patch set. The calling user will be recorded as the real user. + Rebasing on behalf of the uploader is only supported for trivial rebases.
    #[serde(rename = "on_behalf_of_uploader", skip_serializing_if = "Option::is_none")]
    pub on_behalf_of_uploader: Option<bool>,
    /// Map with key-value pairs that are forwarded as options to the commit validation listeners (e.g. can be used to skip certain validations). Which validation options are supported depends on the installed commit validation listeners.
    #[serde(rename = "validation_options", skip_serializing_if = "Option::is_none")]
    pub validation_options: Option<std::collections::HashMap<String, String>>,
    /// Rebase is committed using this email address. Only the registered emails of the calling user or uploader (when on_behalf_of_uploader is true) are considered valid. This option is not supported when rebasing a chain.
    #[serde(rename = "committer_email", skip_serializing_if = "Option::is_none")]
    pub committer_email: Option<String>,
}

impl RebaseInput {
    pub fn new() -> RebaseInput {
        RebaseInput {
            base: None,
            strategy: None,
            allow_conflicts: None,
            on_behalf_of_uploader: None,
            validation_options: None,
            committer_email: None,
        }
    }
}

