/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RebaseInput {
    #[serde(rename = "base", skip_serializing_if = "Option::is_none")]
    pub base: Option<String>,
    #[serde(rename = "strategy", skip_serializing_if = "Option::is_none")]
    pub strategy: Option<String>,
    #[serde(rename = "allow_conflicts", skip_serializing_if = "Option::is_none")]
    pub allow_conflicts: Option<bool>,
    #[serde(rename = "on_behalf_of_uploader", skip_serializing_if = "Option::is_none")]
    pub on_behalf_of_uploader: Option<bool>,
    #[serde(rename = "validation_options", skip_serializing_if = "Option::is_none")]
    pub validation_options: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "committer_email", skip_serializing_if = "Option::is_none")]
    pub committer_email: Option<String>,
}

impl RebaseInput {
    pub fn new() -> RebaseInput {
        RebaseInput {
            base: None,
            strategy: None,
            allow_conflicts: None,
            on_behalf_of_uploader: None,
            validation_options: None,
            committer_email: None,
        }
    }
}

