/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RebaseChainInfo {
    /// List of the unsubmitted ancestors, as ChangeInfo entities. Includes both rebased changes, and previously up-to-date ancestors. The list is ordered by ancestry, where the oldest ancestor is the first.
    #[serde(rename = "rebased_changes", skip_serializing_if = "Option::is_none")]
    pub rebased_changes: Option<Vec<models::ChangeInfo>>,
    /// Whether any of the rebased changes has conflicts due to rebasing.
    #[serde(rename = "contains_git_conflicts", skip_serializing_if = "Option::is_none")]
    pub contains_git_conflicts: Option<bool>,
}

impl RebaseChainInfo {
    pub fn new() -> RebaseChainInfo {
        RebaseChainInfo {
            rebased_changes: None,
            contains_git_conflicts: None,
        }
    }
}

