/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReflogEntryInfo {
    #[serde(rename = "old_id", skip_serializing_if = "Option::is_none")]
    pub old_id: Option<String>,
    #[serde(rename = "new_id", skip_serializing_if = "Option::is_none")]
    pub new_id: Option<String>,
    #[serde(rename = "who", skip_serializing_if = "Option::is_none")]
    pub who: Option<Box<models::GitPerson>>,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
}

impl ReflogEntryInfo {
    pub fn new() -> ReflogEntryInfo {
        ReflogEntryInfo {
            old_id: None,
            new_id: None,
            who: None,
            comment: None,
        }
    }
}

