/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReviewInput {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<std::collections::HashMap<String, i32>>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<std::collections::HashMap<String, Vec<models::CommentInput>>>,
    #[serde(rename = "drafts", skip_serializing_if = "Option::is_none")]
    pub drafts: Option<models::DraftHandling>,
    #[serde(rename = "draft_ids_to_publish", skip_serializing_if = "Option::is_none")]
    pub draft_ids_to_publish: Option<Vec<String>>,
    #[serde(rename = "notify", skip_serializing_if = "Option::is_none")]
    pub notify: Option<models::NotifyHandling>,
    #[serde(rename = "notify_details", skip_serializing_if = "Option::is_none")]
    pub notify_details: Option<std::collections::HashMap<String, models::NotifyInfo>>,
    #[serde(rename = "omit_duplicate_comments", skip_serializing_if = "Option::is_none")]
    pub omit_duplicate_comments: Option<bool>,
    #[serde(rename = "on_behalf_of", skip_serializing_if = "Option::is_none")]
    pub on_behalf_of: Option<String>,
    #[serde(rename = "reviewers", skip_serializing_if = "Option::is_none")]
    pub reviewers: Option<Vec<models::ReviewerInput>>,
    #[serde(rename = "work_in_progress", skip_serializing_if = "Option::is_none")]
    pub work_in_progress: Option<bool>,
    #[serde(rename = "ready", skip_serializing_if = "Option::is_none")]
    pub ready: Option<bool>,
    #[serde(rename = "add_to_attention_set", skip_serializing_if = "Option::is_none")]
    pub add_to_attention_set: Option<Vec<models::AttentionSetInput>>,
    #[serde(rename = "remove_from_attention_set", skip_serializing_if = "Option::is_none")]
    pub remove_from_attention_set: Option<Vec<models::AttentionSetInput>>,
    #[serde(rename = "ignore_automatic_attention_set_rules", skip_serializing_if = "Option::is_none")]
    pub ignore_automatic_attention_set_rules: Option<bool>,
    #[serde(rename = "response_format_options", skip_serializing_if = "Option::is_none")]
    pub response_format_options: Option<Vec<models::ListChangesOption>>,
}

impl ReviewInput {
    pub fn new() -> ReviewInput {
        ReviewInput {
            message: None,
            tag: None,
            labels: None,
            comments: None,
            drafts: None,
            draft_ids_to_publish: None,
            notify: None,
            notify_details: None,
            omit_duplicate_comments: None,
            on_behalf_of: None,
            reviewers: None,
            work_in_progress: None,
            ready: None,
            add_to_attention_set: None,
            remove_from_attention_set: None,
            ignore_automatic_attention_set_rules: None,
            response_format_options: None,
        }
    }
}

