/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReviewerInfo {
    /// The approvals of the reviewer as a map that maps the label names to the approval values (\"-2\", \"-1\", \"0\", \"+1\", \"+2\").
    #[serde(rename = "approvals", skip_serializing_if = "Option::is_none")]
    pub approvals: Option<std::collections::HashMap<String, String>>,
    /// This field is inherited from AccountInfo but is optional here if an unregistered reviewer was added by email. See add-reviewer for details.
    #[serde(rename = "_account_id", skip_serializing_if = "Option::is_none")]
    pub _account_id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "secondary_emails", skip_serializing_if = "Option::is_none")]
    pub secondary_emails: Option<Vec<String>>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "avatars", skip_serializing_if = "Option::is_none")]
    pub avatars: Option<Vec<models::AvatarInfo>>,
    #[serde(rename = "_more_accounts", skip_serializing_if = "Option::is_none")]
    pub _more_accounts: Option<bool>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "inactive", skip_serializing_if = "Option::is_none")]
    pub inactive: Option<bool>,
    #[serde(rename = "deleted", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl ReviewerInfo {
    pub fn new() -> ReviewerInfo {
        ReviewerInfo {
            approvals: None,
            _account_id: None,
            name: None,
            display_name: None,
            email: None,
            secondary_emails: None,
            username: None,
            avatars: None,
            _more_accounts: None,
            status: None,
            inactive: None,
            deleted: None,
            tags: None,
        }
    }
}

