/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitInput {
    /// Deprecated and no longer used. Kept for backwards compatibility.
    #[serde(rename = "wait_for_merge", skip_serializing_if = "Option::is_none")]
    pub wait_for_merge: Option<bool>,
    /// If set, submit the change on behalf of the given user. The value may take any format accepted by the accounts REST API. Using this option requires Submit (On Behalf Of) permission on the branch.
    #[serde(rename = "on_behalf_of", skip_serializing_if = "Option::is_none")]
    pub on_behalf_of: Option<String>,
    /// Notify handling that defines to whom email notifications should be sent after the change is submitted. + Allowed values are NONE, OWNER, OWNER_REVIEWERS and ALL. + If not set, the default is ALL. + Ignored if a post approval diff is present (i.e.
    #[serde(rename = "notify", skip_serializing_if = "Option::is_none")]
    pub notify: Option<models::NotifyHandling>,
    /// Additional information about whom to notify about the update as a map of recipient type to NotifyInfo entity.
    #[serde(rename = "notify_details", skip_serializing_if = "Option::is_none")]
    pub notify_details: Option<std::collections::HashMap<String, models::NotifyInfo>>,
}

impl SubmitInput {
    pub fn new() -> SubmitInput {
        SubmitInput {
            wait_for_merge: None,
            on_behalf_of: None,
            notify: None,
            notify_details: None,
        }
    }
}

