/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SubmitRecordInfoStatus {
    #[serde(rename = "OK")]
    Ok,
    #[serde(rename = "NOT_READY")]
    NotReady,
    #[serde(rename = "CLOSED")]
    Closed,
    #[serde(rename = "FORCED")]
    Forced,
    #[serde(rename = "RULE_ERROR")]
    RuleError,

}

impl std::fmt::Display for SubmitRecordInfoStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ok => write!(f, "OK"),
            Self::NotReady => write!(f, "NOT_READY"),
            Self::Closed => write!(f, "CLOSED"),
            Self::Forced => write!(f, "FORCED"),
            Self::RuleError => write!(f, "RULE_ERROR"),
        }
    }
}

impl Default for SubmitRecordInfoStatus {
    fn default() -> SubmitRecordInfoStatus {
        Self::Ok
    }
}

