/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitTypeInfo {
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<models::SubmitType>,
    #[serde(rename = "configured_value", skip_serializing_if = "Option::is_none")]
    pub configured_value: Option<models::SubmitType>,
    #[serde(rename = "inherited_value", skip_serializing_if = "Option::is_none")]
    pub inherited_value: Option<models::SubmitType>,
}

impl SubmitTypeInfo {
    pub fn new() -> SubmitTypeInfo {
        SubmitTypeInfo {
            value: None,
            configured_value: None,
            inherited_value: None,
        }
    }
}

