/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitRequirementExpressionInfo {
    #[serde(rename = "expression", skip_serializing_if = "Option::is_none")]
    pub expression: Option<String>,
    #[serde(rename = "fulfilled", skip_serializing_if = "Option::is_none")]
    pub fulfilled: Option<bool>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::SubmitRequirementExpressionInfoStatus>,
    #[serde(rename = "passing_atoms", skip_serializing_if = "Option::is_none")]
    pub passing_atoms: Option<Vec<String>>,
    #[serde(rename = "failing_atoms", skip_serializing_if = "Option::is_none")]
    pub failing_atoms: Option<Vec<String>>,
    #[serde(rename = "atom_explanations", skip_serializing_if = "Option::is_none")]
    pub atom_explanations: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "error_message", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
}

impl SubmitRequirementExpressionInfo {
    pub fn new() -> SubmitRequirementExpressionInfo {
        SubmitRequirementExpressionInfo {
            expression: None,
            fulfilled: None,
            status: None,
            passing_atoms: None,
            failing_atoms: None,
            atom_explanations: None,
            error_message: None,
        }
    }
}

