/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitRequirementInput {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "applicability_expression", skip_serializing_if = "Option::is_none")]
    pub applicability_expression: Option<String>,
    #[serde(rename = "submittability_expression", skip_serializing_if = "Option::is_none")]
    pub submittability_expression: Option<String>,
    #[serde(rename = "override_expression", skip_serializing_if = "Option::is_none")]
    pub override_expression: Option<String>,
    #[serde(rename = "allow_override_in_child_projects", skip_serializing_if = "Option::is_none")]
    pub allow_override_in_child_projects: Option<bool>,
}

impl SubmitRequirementInput {
    pub fn new() -> SubmitRequirementInput {
        SubmitRequirementInput {
            name: None,
            description: None,
            applicability_expression: None,
            submittability_expression: None,
            override_expression: None,
            allow_override_in_child_projects: None,
        }
    }
}

