/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SummaryInfo {
    #[serde(rename = "task_summary", skip_serializing_if = "Option::is_none")]
    pub task_summary: Option<Box<models::TaskSummaryInfo>>,
    #[serde(rename = "mem_summary", skip_serializing_if = "Option::is_none")]
    pub mem_summary: Option<Box<models::MemSummaryInfo>>,
    #[serde(rename = "thread_summary", skip_serializing_if = "Option::is_none")]
    pub thread_summary: Option<Box<models::ThreadSummaryInfo>>,
    #[serde(rename = "jvm_summary", skip_serializing_if = "Option::is_none")]
    pub jvm_summary: Option<Box<models::JvmSummaryInfo>>,
}

impl SummaryInfo {
    pub fn new() -> SummaryInfo {
        SummaryInfo {
            task_summary: None,
            mem_summary: None,
            thread_summary: None,
            jvm_summary: None,
        }
    }
}

