/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TestSubmitRuleInfo {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "error_message", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(rename = "ok", skip_serializing_if = "Option::is_none")]
    pub ok: Option<std::collections::HashMap<String, models::AccountInfo>>,
    #[serde(rename = "reject", skip_serializing_if = "Option::is_none")]
    pub reject: Option<std::collections::HashMap<String, models::AccountInfo>>,
    #[serde(rename = "need", skip_serializing_if = "Option::is_none")]
    pub need: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "may", skip_serializing_if = "Option::is_none")]
    pub may: Option<std::collections::HashMap<String, models::AccountInfo>>,
    #[serde(rename = "impossible", skip_serializing_if = "Option::is_none")]
    pub impossible: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl TestSubmitRuleInfo {
    pub fn new() -> TestSubmitRuleInfo {
        TestSubmitRuleInfo {
            status: None,
            error_message: None,
            ok: None,
            reject: None,
            need: None,
            may: None,
            impossible: None,
        }
    }
}

