/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TimeFormat {
    #[serde(rename = "HHMM_12")]
    Hhmm12,
    #[serde(rename = "HHMM_24")]
    Hhmm24,

}

impl std::fmt::Display for TimeFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Hhmm12 => write!(f, "HHMM_12"),
            Self::Hhmm24 => write!(f, "HHMM_24"),
        }
    }
}

impl Default for TimeFormat {
    fn default() -> TimeFormat {
        Self::Hhmm12
    }
}

