/*
 * Gerrit Code Review REST API
 *
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserConfigInfo {
    /// Username that is displayed in the Gerrit Web UI and in e-mail notifications if the full name of the user is not set.
    #[serde(rename = "anonymous_coward_name", skip_serializing_if = "Option::is_none")]
    pub anonymous_coward_name: Option<String>,
}

impl UserConfigInfo {
    pub fn new() -> UserConfigInfo {
        UserConfigInfo {
            anonymous_coward_name: None,
        }
    }
}

